---
title: "Referências Bibliográficas"
output:
  html_document:
    toc: false
---

Não existem referências únicas para esta disciplina. Abaixo estão
algumas referências divididas por assunto. Ao longo do curso serão
indicadas as referências mais adequadas em cada etapa.

## Referências básicas

- Bruce, C.
  [Novas aventuras científicas de Sherlock Holmes: casos de lógica, matemática e probabilidade](http://www.zahar.com.br/livro/novas-aventuras-cientificas-de-sherlock-holmes).
  Rio de Janeiro: Zahar, 2003.
- Hilborn, R; Mangel, M.
  [The ecological detective: confronting models with data](http://press.princeton.edu/titles/5987.html).
  Princeton University Press, 1997.
- Huff, D.
  [Como mentir com estatística](http://www.intrinseca.com.br/livro/624/).
  Rio de Janeiro: Intrínseca, 2016.
- Mlodinow, L.
  [O andar do bêbado. Como o acaso determina nossas vidas](http://zahar.com.br/livro/o-andar-do-b%C3%AAbado).
  Rio de Janeiro: Zahar, 2009.
- Salsburg, D.
  [Uma senhora toma chá. Como a estatística revolucionou a ciência no século XX](http://www.zahar.com.br/livro/uma-senhora-toma-cha).
  Rio de Janeiro: Zahar, 2009.
- Wheelan, C.
  [Estatística: o que é, para que serve, como funciona](http://www.zahar.com.br/livro/estatistica).
  Rio de Janeiro: Zahar, 2016.

## Metodologia científica

- Lakatos, EM; Marconi, MA.
[Fundamentos de metodologia científica](http://www.grupogen.com.br/fundamentos-metodologia-cientifica).
São Paulo: Atlas, 2010.
- Marconi, MA.; Lakatos, EM.
  [Metodologia do trabalho científico](http://www.grupogen.com.br/metodologia-trabalho-cientifico). São Paulo: Atlas, 2007.

## Filosofia da ciência

- Alves, R.
  [Filosofia da ciência: introdução ao jogo e a suas regras](http://www.loyola.com.br/produtos_descricao.asp?lang=pt_br&codigo_produto=4163).
  São Paulo: Loyola, 2007.
- Dutra, LHA.
  [Introdução à teoria da ciência](http://www.egov.ufsc.br/portal/conteudo/introdu%C3%A7%C3%A3o-%C3%A0-teoria-da-ci%C3%AAncia).
  Florianópolis: Editora da UFSC, 2009.
- Kuhn, TS.
  [A estrutura das revoluções científicas](http://www.editoraperspectiva.com.br/index.php?apg=cat&npr=333).
  São Paulo: Perspectiva, 2011.
